export const DEFAULT_OPTIONS = {
  PATH_SEPARATOR: '/',
  VARIABLE_START: ':',
  VARIABLE_END: '',
  VARIABLE_ENUM_START: '(',
  VARIABLE_ENUM_END: ')',
  VARIABLE_ENUM_SEPARATOR: '|',
  VARIABLE_OPTIONAL_IDENTIFIER: '?',
};
